version: '3.9'

services:

  dev-db:
    image: postgres:16.2-alpine3.19
    restart: always
    env_file:
      - ./.env
    ports:
      - "5433:5433"

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: none
      PGADMIN_DEFAULT_PASSWORD: none